version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    container_name: keycloak-app
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@123
      KC_DB: oracle
      KC_DB_URL: jdbc:oracle:thin:@//host.docker.internal:1521/ORCLPDB
      KC_DB_USERNAME: KEYCLOAK
      KC_DB_PASSWORD: keycloak123
      KC_PROXY: edge
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./drivers:/opt/keycloak/providers:ro
      - ./import:/opt/keycloak/data/import:ro
      - ./certs:/certs:ro
      - ./qlvb-theme:/opt/keycloak/themes/qlvb-theme:ro
    command:
      - start-dev
