// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using reviewApi.Models;

#nullable disable

namespace reviewApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414002150_MigrateToGuid")]
    partial class MigrateToGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("reviewApi.Models.Classification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<Guid>("CriteriaSetId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("MinScore")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("VirtualId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaSetId", "Code")
                        .IsUnique();

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("reviewApi.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("Content")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("ReplyToCommentId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("ReplyToCommentId");

                    b.HasIndex("UserId");

                    b.HasIndex("EvaluationId", "CreatedAt");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("reviewApi.Models.CommentAudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AudioType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentAudios");
                });

            modelBuilder.Entity("reviewApi.Models.CommentFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentFiles");
                });

            modelBuilder.Entity("reviewApi.Models.CommentReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CommentId", "UserId", "Emoji")
                        .IsUnique();

                    b.ToTable("CommentReactions");
                });

            modelBuilder.Entity("reviewApi.Models.Criteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("CriteriaSetId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("DisplayCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("VirtualCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("VirtualParentCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaSetId", "VirtualCode")
                        .IsUnique();

                    b.ToTable("Criterias");
                });

            modelBuilder.Entity("reviewApi.Models.CriteriaSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("ApplicableMonths")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ApplicableYears")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("CriteriaSets");
                });

            modelBuilder.Entity("reviewApi.Models.CriteriaSetObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("CriteriaSetId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("EvaluationObjectId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationObjectId");

                    b.HasIndex("CriteriaSetId", "EvaluationObjectId")
                        .IsUnique();

                    b.ToTable("CriteriaSetObjects");
                });

            modelBuilder.Entity("reviewApi.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("reviewApi.Models.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("CriteriaSetId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal?>("ManagerScore")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("Month")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("SelfScore")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Year")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaSetId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("UserId", "Year", "Month");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("FlowCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("FlowCode")
                        .IsUnique();

                    b.ToTable("EvaluationFlows");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("CriteriaSetId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaSetId");

                    b.HasIndex("FlowId", "CriteriaSetId")
                        .IsUnique();

                    b.ToTable("EvaluationFlowCriterias");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FlowId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("EvaluationFlowDepartments");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("EvaluationObjectId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("VirtualCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("VirtualParentCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationObjectId");

                    b.HasIndex("FlowId", "VirtualCode")
                        .IsUnique();

                    b.ToTable("EvaluationFlowObjects");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("VirtualCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("VirtualParentCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("FlowId", "VirtualCode")
                        .IsUnique();

                    b.ToTable("EvaluationFlowRoles");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("EvaluationObjects");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObjectRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("EvaluationObjectId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationObjectId");

                    b.HasIndex("UserId");

                    b.ToTable("EvaluationObjectRoles");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal?>("ManagerScore")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("SelfScore")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("VirtualCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId", "VirtualCode")
                        .IsUnique();

                    b.ToTable("EvaluationScores");
                });

            modelBuilder.Entity("reviewApi.Models.ReportType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("ApplicableMonths")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ApplicableYears")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ReportTypes");
                });

            modelBuilder.Entity("reviewApi.Models.ReportTypeCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("CriteriaSetId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ReportTypeId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaSetId");

                    b.HasIndex("ReportTypeId", "CriteriaSetId")
                        .IsUnique();

                    b.ToTable("ReportTypeCriterias");
                });

            modelBuilder.Entity("reviewApi.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("reviewApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("reviewApi.Models.Classification", b =>
                {
                    b.HasOne("reviewApi.Models.CriteriaSet", "CriteriaSet")
                        .WithMany("Classifications")
                        .HasForeignKey("CriteriaSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaSet");
                });

            modelBuilder.Entity("reviewApi.Models.Comment", b =>
                {
                    b.HasOne("reviewApi.Models.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.Comment", "ReplyToComment")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("reviewApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("ReplyToComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("reviewApi.Models.CommentAudio", b =>
                {
                    b.HasOne("reviewApi.Models.Comment", "Comment")
                        .WithMany("Audios")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("reviewApi.Models.CommentFile", b =>
                {
                    b.HasOne("reviewApi.Models.Comment", "Comment")
                        .WithMany("Files")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("reviewApi.Models.CommentReaction", b =>
                {
                    b.HasOne("reviewApi.Models.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("reviewApi.Models.Criteria", b =>
                {
                    b.HasOne("reviewApi.Models.CriteriaSet", "CriteriaSet")
                        .WithMany("Criterias")
                        .HasForeignKey("CriteriaSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaSet");
                });

            modelBuilder.Entity("reviewApi.Models.CriteriaSetObject", b =>
                {
                    b.HasOne("reviewApi.Models.CriteriaSet", "CriteriaSet")
                        .WithMany("CriteriaSetObjects")
                        .HasForeignKey("CriteriaSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.EvaluationObject", "EvaluationObject")
                        .WithMany()
                        .HasForeignKey("EvaluationObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriteriaSet");

                    b.Navigation("EvaluationObject");
                });

            modelBuilder.Entity("reviewApi.Models.Department", b =>
                {
                    b.HasOne("reviewApi.Models.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("reviewApi.Models.Evaluation", b =>
                {
                    b.HasOne("reviewApi.Models.CriteriaSet", "CriteriaSet")
                        .WithMany()
                        .HasForeignKey("CriteriaSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("reviewApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriteriaSet");

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowCriteria", b =>
                {
                    b.HasOne("reviewApi.Models.CriteriaSet", "CriteriaSet")
                        .WithMany()
                        .HasForeignKey("CriteriaSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.EvaluationFlow", "EvaluationFlow")
                        .WithMany("Criterias")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaSet");

                    b.Navigation("EvaluationFlow");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowDepartment", b =>
                {
                    b.HasOne("reviewApi.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.EvaluationFlow", "EvaluationFlow")
                        .WithMany("Departments")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("EvaluationFlow");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowObject", b =>
                {
                    b.HasOne("reviewApi.Models.EvaluationObject", "EvaluationObject")
                        .WithMany()
                        .HasForeignKey("EvaluationObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.EvaluationFlow", "EvaluationFlow")
                        .WithMany("Objects")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationFlow");

                    b.Navigation("EvaluationObject");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlowRole", b =>
                {
                    b.HasOne("reviewApi.Models.EvaluationFlow", "EvaluationFlow")
                        .WithMany("Roles")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvaluationFlow");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObjectRole", b =>
                {
                    b.HasOne("reviewApi.Models.EvaluationObject", "EvaluationObject")
                        .WithMany("EvaluationObjectRoles")
                        .HasForeignKey("EvaluationObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvaluationObject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationScore", b =>
                {
                    b.HasOne("reviewApi.Models.Evaluation", "Evaluation")
                        .WithMany("EvaluationScores")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("reviewApi.Models.ReportTypeCriteria", b =>
                {
                    b.HasOne("reviewApi.Models.CriteriaSet", "CriteriaSet")
                        .WithMany()
                        .HasForeignKey("CriteriaSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.ReportType", "ReportType")
                        .WithMany("ReportTypeCriterias")
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaSet");

                    b.Navigation("ReportType");
                });

            modelBuilder.Entity("reviewApi.Models.User", b =>
                {
                    b.HasOne("reviewApi.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("reviewApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("reviewApi.Models.Comment", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("Files");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("reviewApi.Models.CriteriaSet", b =>
                {
                    b.Navigation("Classifications");

                    b.Navigation("CriteriaSetObjects");

                    b.Navigation("Criterias");
                });

            modelBuilder.Entity("reviewApi.Models.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("reviewApi.Models.Evaluation", b =>
                {
                    b.Navigation("EvaluationScores");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationFlow", b =>
                {
                    b.Navigation("Criterias");

                    b.Navigation("Departments");

                    b.Navigation("Objects");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("reviewApi.Models.EvaluationObject", b =>
                {
                    b.Navigation("EvaluationObjectRoles");
                });

            modelBuilder.Entity("reviewApi.Models.ReportType", b =>
                {
                    b.Navigation("ReportTypeCriterias");
                });

            modelBuilder.Entity("reviewApi.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
